### ISSUE TITLE
Hex colors and actual grid colors differ

### ISSUE THREAD

**Issue by Benosika** [onlineth/HSLa-Explorer#1]
Hi, thanks again Tom for the modification! Just one small note:

I pasted this color ( #0A97B7 ) in the tool but couldn't track it in the matrix; I could only track hue variants (with their brightness hierarchies) that are similar to that color, but not it itself.

The reason I need this color to appear as well, most preferably lessermost, leftest color (Image attached) is to use hue variants that come after this, which will be softer, to use them as "easier colors" in a palette hierarchy.

I personally would glad using such feature and I will gladly give 50 more bounty for adding it.

![iii](https://cloud.githubusercontent.com/assets/13021900/18573764/5f401932-7bcf-11e6-8479-73762add836e.PNG)

**Comment by onlineth** [comment]
Hmm, let me take a closer look

**Comment by onlineth** [comment]
Ok, I just pushed a commit that should fix this issue and purged CloudFlare's cache, please let me know if this works for you @Benosika (no extra bounty needed, this should've been fixed from the start:)

**Comment by Benosika** [comment]
Donno why but for me another color gave similar results... 
![aaa](https://cloud.githubusercontent.com/assets/13021900/18593598/d2b281a0-7c44-11e6-84ba-0fd664ec5096.png)

**Comment by onlineth** [comment]
Oh, now I understand your question. Hmm, a color converter was used called [Color2Color](https://github.com/metaloha/color2color). This works by taking the hsla from the colored box above the input field and converts the color format to hex, which doesn't appear to be doing the best job :/. I'll submit a ticket on their end to see how we can resolve this.

**Comment by onlineth** [comment]
Ah, now I understand your question, this was actually an error from the original script (it did not convert the color correctly). I've pushed a change that uses another script dedicated for converting colors correctly from one format to another. That should fix this issue.

**Comment by onlineth** [comment]
Please let me know if this does the trick

**Comment by Benosika** [comment]
I looked at https://hsla.onlineth.com/ but still saw no change in the color adjustment (pasted color vs down-left corner non-black color)... :\

**Comment by onlineth** [comment]
Try a private browser session. The old script may be cached still as it is on mine,
[Imgur](http://i.imgur.com/jSQ8vyK.png)

**Comment by Benosika** [comment]
Wired, I checked with 2 browsers after total manual flush cache from "beginning of usage". In the second one (Chrome) I didn't try the tool AFAICR.

Yet, I still see a mismatch... Donno... :|

**Comment by onlineth** [comment]
Hmm, try this, could you download and extract this and run it from there?
https://github.com/onlineth/HSLa-Explorer/archive/master.zip

**Comment by Benosika** [comment]
Ran it locally from Firefox and that's my report (thank you for all the time you invest in this!!!):
![untitled](https://cloud.githubusercontent.com/assets/13021900/18610035/b9fc16a0-7d19-11e6-9cf1-317ab13872f9.png)

**Comment by Benosika** [comment]
2. There seems to be a slightly easy mismatch between the pasted color and the one picked from the 2 rectangulars (hsla and rgba).

**Comment by onlineth** [comment]
Ah ha! Ya, it's not my problem, it's color2color's:)

**Comment by onlineth** [comment]
ok, so, I use color2color for color format conversion. Type in the hex, #f35df4, then click the dropdown and bring that down to hsla, copy that and paste it in here: http://www.w3schools.com/colors/colors_hsl.asp then go back to the hsla explorer and click the drop down to hex, you'll see #f35df4. color2color thinks #f35df4 = hsla(300,86%,66%,1) but that's not true. Take note of the change also with rgba change when you go from hex to hsla to hex again.

**Comment by onlineth** [comment]
Actually, it looks like that the format HSLa itself may not be possible to convert with 100% accuracy back to hex, but as you can see it get's really close.

**Comment by Benosika** [comment]
wow... I am a humble JS learner. I hope you guys could bring this to 100% accuracy... It will be the best color hierarchy tool ever created, I think..

**Comment by onlineth** [comment]
@Benosika So, color2color added a patch that I believed helped conform to other tools out there but here's the thing, collisions between Hex and HSLA are inevitable.  I believe there are more Hex values then HSLA values so some hex values may equal the same HSLA value. The colors will be so close that it will be pretty hard to distinguish. This is why Chris, the original author, I think added both the HSLA box and the RGBA box, by using a color dropper, there may possibly be an *extremely* slight difference in the color. Does this answer your question/issue?

**Comment by Benosika** [comment]
Indeed it is. Thanks !

**Comment by onlineth** [comment]
Great:)
